---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  creationTimestamp: null
  labels:
    app: magento2-testenv
    name: magento2-testenv-db
  name: magento2-testenv-db

spec:
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: magento2-testenv
        name: magento2-testenv-db

    spec:
      containers:
      - name: magento2-testenv-db
        image: mysql:5.6.23
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: myrootpassword
        - name: MYSQL_USER
          value: magento
        - name: MYSQL_PASSWORD
          value: magento
        - name: MYSQL_DATABASE
          value: magento
        volumeMounts:
          - name: magento2-testenv-db-pvc
            mountPath: /var/lib/mysql

      volumes:
        - name: magento2-testenv-db-pvc
          persistentVolumeClaim:
            claimName: magento2-plugin-db-pvc
