apiVersion: v1
kind: Service
metadata:
  labels:
    app: magento2-testenv
    name: magento2-testenv-db
  name: magento2-testenv-db
spec:
  ports:
    - port: 3306
      protocol: TCP
      name: magento2-testenv-db
  selector:
    app: magento2-testenv
    name: magento2-testenv-db
