<?php
/**
 * @var $block \Metrilo\Analytics\Block\System\Config\Button\Import
 */
?>
<?php if ($this->buttonEnabled()): ?>
    <?php $import = $this->getImport(); ?>
    <?php $storeId = $import->getStoreId(); ?>
    <div class="pp-buttons-container">
        <button id="<?php echo $block->getHtmlId() ?>" onclick="return false;">
            <span><?php echo __('Import orders'); ?></span>
        </button>
    </div>

    <script>
        require(['jquery'], function ($) {
            var params = {
                internUrl:"<?php echo $block->getInternUrl() ?>",
                apiKeyId: "#<?php echo $block->getApiKeyId() ?>",
                htmlId: "#<?php echo $block->getHtmlId() ?>",
                loadConfigUrl: "<?php echo $block->getLoadConfigUrl() ?>"
            };
            $("#<?php echo $block->getHtmlId() ?>").on( "click", function() {
                alert('hello');
                console.log(params);
            });
        });
    </script>
<?php endif; ?>