<?php
/**
 * @var $block \Metrilo\Analytics\Block\System\Config\Button\Import
 */
?>
<?php if ($block->buttonEnabled()): ?>
    <?php /** @var \Metrilo\Analytics\Model\Import $import */
    $import = $block->getImport(); ?>
    <?php $storeId = $import->getStoreId(); ?>
    <div class="pp-buttons-container">
        <button id="<?php echo $block->getHtmlId() ?>" onclick="return false;">
            <span><?php echo __('Import'); ?></span>
        </button>
    </div>
    <script>
    require([
        'jquery',
        'metriloImport'
    ], function($, metrilo) {
        $("#<?php echo $block->getHtmlId() ?>").import({
            storeId: <?php echo $storeId; ?>,
            customerChunks: <?php echo $import->getCustomerChunks($storeId); ?>,
            categoryChunks: <?php echo $import->getCategoryChunks($storeId); ?>,
            productChunks: <?php echo $import->getProductChunks($storeId); ?>,
            orderChunks: <?php echo $import->getOrderChunks($storeId); ?>,
            importStatus: 1,
            submitUrl: '<?php echo $block->getAjaxUrl(); ?>',
            messageSelector: '#metrilo_import_status'
        });
    });
    </script>
    <div id="metrilo_import_status"></div>
    <?php return; ?>
<?php endif; ?>

