<?php
/**
 * @var $block \Metrilo\Analytics\Block\System\Config\Button\Import
 */
?>
<?php if ($block->buttonEnabled()): ?>
    <?php /** @var \Metrilo\Analytics\Helper\DataSerializer $import */
        $import = $block->getImport();
        $orderImport = $block->getOrderImport();
        $storeId = $block->getStoreId();
    ?>
    <div class="pp-buttons-container">
        <button id="<?php echo $block->getHtmlId() ?>" onclick="return false;">
            <span><?php echo __('Import'); ?></span>
        </button>
    </div>
    <script>
    require([
        'jquery',
        'metriloImport'
    ], function($, metrilo) {
        $("#<?php echo $block->getHtmlId() ?>").import({
            storeId: <?php echo $storeId; ?>,
            customersChunks: <?php echo $import->getCustomerChunks($storeId); ?>,
            categoriesChunks: <?php echo $import->getCategoryChunks($storeId); ?>,
            productsChunks: <?php echo $import->getProductChunks($storeId); ?>,
            ordersChunks: <?php echo $orderImport->orderData->getOrderChunks($storeId); ?>,
            submitUrl: '<?php echo $block->getAjaxUrl(); ?>',
            messageSelector: '#metrilo_import_status'
        });
    });
    </script>
    <div id="metrilo_import_status"></div>
    <?php return; ?>
<?php endif; ?>

