<?php
/**
 * @var \Metrilo\Analytics\Block\Analytics $block
 * @var \Magento\Framework\Escaper $escaper
 */

$url = $block->getLibraryUrl();
$events = $block->getEvents();
?>
<script>
    require(['<?= $escaper->escapeUrl($url) ?>'], function(){
        <?php foreach ($events as $event): ?>
            <?= $escaper->escapeJs($event) ?>
        <?php endforeach; ?>
    });
</script>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "metrilo-private-data": {
                        "component": "Metrilo_Analytics/js/private-data"
                    }
                }
            }
        }
    }
</script>
