<?php
/**
 * @see Metrilo\Analytics\Block\Analytics
 */

$url   = $block->getLibraryUrl();
$events = $block->getEvents();
?>
<script type="text/javascript">
    require(['<?php echo $url; ?>'], function(){
        <?php foreach($events as $event) { echo $event; } ?>
    });
</script>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "metrilo-private-data": {
                        "component": "Metrilo_Analytics/js/private-data"
                    }
                }
            }
        }
    }
</script>
