<?php
/**
 * @see Metrilo\Analytics\Block\Analytics
 */

/** @var Metrilo\Analytics\Block\Analytics $events */
$events = $block->getEvents();
?>
<script type="text/javascript">
    require(['<?php echo $block->getApiEndpoint(); ?>' + '/tracking.js?token=' + '<?php echo $block->getApiToken(); ?>'], function(){
        <?php foreach ($events as $event) : ?>
            console.log('<?php echo 'Event Type: ' . $event['type']; ?>');
            <?php if($event['method'] == 'identify') : ?>
                metrilo.identify("<?php echo $event['data']['id']; ?>", <?php echo json_encode($event['data']['params']); ?>);
            <?php elseif($event['method'] == 'track') : ?>
                <?php if($event['type'] == 'view_product') : ?>
                    window.metrilo.viewProduct(<?php echo $event['data']['productId']; ?>);
                <?php endif; ?>
            <?php endif; ?>
        <?php endforeach; ?>
    });
</script>
